import { jsPDF } from 'jspdf';

export function exportToPdf(title: string, content: string | Record<string, any>): void {
  const doc = new jsPDF();
  const margin = 15;
  let cursorY = 20;
  const pageHeight = doc.internal.pageSize.height;
  const maxLineWidth = 180;

  // Header banner
  doc.setFillColor(37, 99, 235); // Brand blue #2563eb
  doc.rect(0, 0, 210, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(' AI - LOCAL BUSINESS GROWTH ADVISOR', margin, 15);

  cursorY = 35;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title.toUpperCase(), margin, cursorY);
  cursorY += 10;

  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, cursorY, margin + maxLineWidth, cursorY);
  cursorY += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  const formattedText = typeof content === 'string' ? content : JSON.stringify(content, null, 2);
  const lines = doc.splitTextToSize(formattedText, maxLineWidth);

  lines.forEach((line: string) => {
    if (cursorY > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(line, margin, cursorY);
    cursorY += 6;
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by  AI Local Business Growth Advisor - Page ${i} of ${pageCount}`, margin, pageHeight - 10);
  }

  const safeFilename = title.toLowerCase().replace(/[^a-z0-9]/g, '_');
  doc.save(`${safeFilename}_report.pdf`);
}
